
import React from 'react';
import type { Medicine, BillItem } from '../types';

interface DosageInstructionsProps {
    items: BillItem[];
    medicines: Medicine[];
}

const DosageInstructions: React.FC<DosageInstructionsProps> = ({ items, medicines }) => {
    // Collect all items that have directions in the master catalog
    const itemsWithDirections = items.map(item => {
        // Try to find the master medicine record by name (most reliable as ID link may vary in local storage state)
        const master = medicines.find(m => m.name.toLowerCase().trim() === item.name.toLowerCase().trim());
        if (master && master.directions && master.directions.trim() !== '') {
            return {
                name: item.name,
                directionsEn: master.directions,
                directionsAs: translateToAssamese(master.directions)
            };
        }
        return null;
    }).filter((val): val is { name: string, directionsEn: string, directionsAs: string } => val !== null);

    if (itemsWithDirections.length === 0) return null;

    return (
        <div className="dosage-instructions-page mt-10 p-8 bg-white text-black print:mt-0 print:page-break-before-always min-h-fit font-sans border-t-2 border-dashed border-gray-400">
            <div className="text-center mb-8 border-b-2 border-black pb-4">
                <h2 className="text-xl font-black uppercase tracking-widest text-gray-900 leading-none mb-2">
                    Dosage Instructions
                </h2>
                <h3 className="text-lg font-bold text-gray-700 leading-none">
                    ব্যৱহাৰৰ নিৰ্দেশাৱলী
                </h3>
            </div>

            <table className="w-full border-collapse border-2 border-black text-sm">
                <thead>
                    <tr className="bg-gray-100">
                        <th className="border-2 border-black p-3 text-left font-black uppercase w-[30%]">Medicine Name / ঔষধৰ নাম</th>
                        <th className="border-2 border-black p-3 text-left font-black uppercase w-[35%]">Dosage (English)</th>
                        <th className="border-2 border-black p-3 text-left font-black uppercase w-[35%]">Dosage (Assamese)</th>
                    </tr>
                </thead>
                <tbody>
                    {itemsWithDirections.map((item, idx) => (
                        <tr key={idx} className="border-b border-black last:border-b-0">
                            <td className="border-2 border-black p-3 font-black uppercase bg-slate-50/50">{item.name}</td>
                            <td className="border-2 border-black p-3 font-semibold text-blue-900 italic">{item.directionsEn}</td>
                            <td className="border-2 border-black p-3 font-bold text-gray-950">{item.directionsAs}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <div className="mt-12 p-4 border border-black bg-gray-50 rounded-none italic text-center">
                <p className="text-sm font-bold text-red-700 mb-1">
                    * Please follow your doctor's prescription strictly.
                </p>
                <p className="text-sm font-bold text-red-700">
                    * অনুগ্ৰহ কৰি আপোনাৰ চিকিৎসকৰ পৰামৰ্শ কঠোৰভাৱে পালন কৰক।
                </p>
            </div>

            <div className="mt-20 flex justify-between items-end opacity-50">
                <div className="text-[10px] font-bold uppercase tracking-tighter">
                    <p>Generated by MDXERA ERP</p>
                    <p>Healthcare Companion</p>
                </div>
                <div className="w-48 border-t border-black pt-1 text-center font-bold text-[10px] uppercase">
                    Pharmacist Sign
                </div>
            </div>
        </div>
    );
};

/**
 * Basic pattern-based translation helper for common medical dosage formats.
 * This ensures the Assamese column is meaningful even if the master record only has English.
 */
function translateToAssamese(text: string): string {
    if (!text) return '-';
    
    let t = text.toLowerCase();
    
    // Pattern Dictionary
    const replacements: Record<string, string> = {
        "1-0-1": "ৰাতিপুৱা ১ টা - ৰাতি ১ টা",
        "1-1-1": "ৰাতিপুৱা ১ টা - দুপৰীয়া ১ টা - ৰাতি ১ টা",
        "0-0-1": "কেৱল ৰাতি ১ টা",
        "1-0-0": "কেৱল ৰাতিপুৱা ১ টা",
        "0-1-0": "কেৱল দুপৰীয়া ১ টা",
        "after meal": "আহাৰৰ পাছত",
        "after meals": "আহাৰৰ পাছত",
        "before meal": "আহাৰৰ আগত",
        "before meals": "আহাৰৰ আগত",
        "empty stomach": "খালী পেটত",
        "at bedtime": "শোৱাৰ আগত",
        "twice daily": "দিনত দুবাৰকৈ",
        "thrice daily": "দিনত তিনিবাৰকৈ",
        "once daily": "দিনত এবাৰকৈ",
        "twice a day": "দিনত দুবাৰকৈ",
        "thrice a day": "দিনত তিনিবাৰকৈ",
        "once a day": "দিনত এবাৰকৈ",
        "morning": "ৰাতিপুৱা",
        "night": "ৰাতি",
        "afternoon": "দুপৰীয়া",
        "evening": "আবেলি"
    };

    let result = text;
    
    // Try complex pattern matches first
    for (const [key, value] of Object.entries(replacements)) {
        if (t.includes(key)) {
            // Replace matching parts or return full translation if the string is just that pattern
            if (t.trim() === key) return value;
            // Otherwise, we could do partial replacement, but for medicine dosage, 
            // usually the pattern is standard. We'll return the value for matched patterns.
            return value;
        }
    }
    
    // Fallback: If no common pattern is found, we just return the original text 
    // to ensure no information is lost, but formatted nicely.
    return "নিৰ্দেশ অনুসৰণ কৰক: " + text;
}

export default DosageInstructions;
